name: p_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  random_string: ^2.3.1
  fluttertoast: ^8.2.4
  firebase_storage: ^11.6.11
  flutter:
    sdk: flutter
  http: ^1.2.1
  path: ^1.9.0
  file_picker: ^8.0.0+1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
