// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUrB1uaCZTMzJeLw65MghEN6FmHSQQBoI',
    appId: '1:814894867300:web:9061b8f944629d666d9071',
    messagingSenderId: '814894867300',
    projectId: 'vickeypedia-19d2c',
    authDomain: 'vickeypedia-19d2c.firebaseapp.com',
    storageBucket: 'vickeypedia-19d2c.appspot.com',
    measurementId: 'G-PYFBNWM7CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFu_WIIqoqAbqPGQ6zppWmsDj2e3rdkLA',
    appId: '1:814894867300:android:6d8e959d66ea2c976d9071',
    messagingSenderId: '814894867300',
    projectId: 'vickeypedia-19d2c',
    storageBucket: 'vickeypedia-19d2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR74QsCPXFFRC5FJZStWYRJbRoEH9pA-U',
    appId: '1:814894867300:ios:5ee1f55822ea290e6d9071',
    messagingSenderId: '814894867300',
    projectId: 'vickeypedia-19d2c',
    storageBucket: 'vickeypedia-19d2c.appspot.com',
    iosBundleId: 'com.example.p1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR74QsCPXFFRC5FJZStWYRJbRoEH9pA-U',
    appId: '1:814894867300:ios:9eff2edf9170afa96d9071',
    messagingSenderId: '814894867300',
    projectId: 'vickeypedia-19d2c',
    storageBucket: 'vickeypedia-19d2c.appspot.com',
    iosBundleId: 'com.example.p1.RunnerTests',
  );
}
